In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

csv_path = Path.cwd() / "datasets" / "Housing.csv"
df = pd.read_csv(csv_path)

In [2]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
binary_cols = [
    'mainroad',
    'guestroom',
    'basement',
    'hotwaterheating',
    'airconditioning',
    'prefarea'
]

df[binary_cols] = df[binary_cols].replace({'yes': 1, 'no': 0})

C:\Users\welcome\AppData\Local\Temp\ipykernel_53480\3295332638.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[binary_cols] = df[binary_cols].replace({'yes': 1, 'no': 0})

In [4]:
X = df[['area', 'bedrooms', 'bathrooms', 'stories', 'parking',
        'mainroad', 'guestroom', 'basement', 'prefarea',
        'hotwaterheating', 'airconditioning']]
y = df['price']

X.shape

(545, 11)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
model = Ridge(alpha=1.0)
model.fit(X_train, y_train)

Ridge()

In [8]:
y_pred = model.predict(X_test)

print(y_test.head())
print(y_pred[:5])

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
Name: price, dtype: int64
[5397092.25895284 7061125.53406    2995416.07445016 4536345.61567429
 3056111.60429506]

In [9]:
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  :", r2_score(y_test, y_pred))

MAE : 979146.9369349992
MSE : 1801382721602.1348
RMSE: 1342155.9974914
R2  : 0.6436130800834199

In [10]:
print("Intercept:", model.intercept_)

coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})
coef_df = coef_df.reindex(
    coef_df["Coefficient"].abs().sort_values(ascending=False).index
).reset_index(drop=True)

coef_df

Intercept: 4706527.385321101

            Feature    Coefficient
0         bathrooms  527985.775397
1              area  522341.500566
2   airconditioning  372613.592060
3           stories  365061.195413
4          prefarea  269138.205509
5           parking  211391.820359
6          basement  207896.979267
7   hotwaterheating  155526.536195
8          mainroad  144365.780842
9         guestroom   93745.390590
10         bedrooms   59512.470336